---
- name: Check if update is needed
  ansible.builtin.include_tasks:
    file: noauto_check_update_needed.yml
  when: neovim_update_needed is not defined

- name: Install new plugin version
  when: neovim_update_needed | bool
  block:
    - name: Ensure Lazy plugins are updated
      ansible.builtin.command:
        cmd: "nvim --headless '+Lazy! sync' +qa"
      changed_when: true

    - name: Ensure Mason is updated
      ansible.builtin.command:
        cmd: "nvim --headless '+MasonUpdate' +qa"
      changed_when: true

    - name: Ensure Mason tools are updated
      ansible.builtin.command:
        cmd: "nvim --headless '+MasonToolsUpdateSync' +qa"
      changed_when: true

    - name: Update timestamp file
      ansible.builtin.shell:
        cmd: "echo '{{ neovim_current_time.stdout }}' > {{ neovim_update_timestamp_file }}"
      changed_when: true
