---
- name: Check installed neovim version
  block:
    - name: Get installed neovim version
      ansible.builtin.command:
        cmd: "nvim --version"
      ignore_errors: true
      changed_when: false
      failed_when: false
      register: neovim_installed_version_cmd

    - name: Extract only the version into a variable
      ansible.builtin.set_fact:
        neovim_installed_version: "{{ (neovim_installed_version_cmd.stdout | regex_search('NVIM\\ v([\\d.]+)', '\\1'))[0] | default('') }}"

    - name: Debug installed neovim version
      ansible.builtin.debug:
        var: neovim_installed_version
