---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "pluggero/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.timer, ansible.posix.profile_tasks, ansible.posix.profile_roles
      host_key_checking: false
    ssh_connection:
      pipelining: true
      ssh_args: -o ControlMaster=auto -o ControlPersist=60s
    callback_profile_roles:
      summary_only: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
